version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - /ruta/al/volumen:/var/lib/mysql
    ports:
      - "3306:3306"